-- CREATE DATABASE heroku_2113f3ce5ec2950;
USE heroku_2113f3ce5ec2950;

CREATE TABLE CLIENT (
    PHONE INT PRIMARY KEY
);

CREATE TABLE ORDERS (
    PHONE INT,
    ITEM VARCHAR(100),
    STREET VARCHAR(200),
    STAMP VARCHAR(50),
    CONSTRAINT DELIVER PRIMARY KEY (STAMP, PHONE)
);

CREATE TABLE MENU (
    ITEM VARCHAR(100), 
    TYPE VARCHAR(25)
);

CREATE TABLE SHAKE (
    ITEM VARCHAR(100),
    TYPE VARCHAR(25)
);
CREATE TABLE TEA (
    ITEM VARCHAR(100),
    TYPE VARCHAR(25)
);
CREATE TABLE ALOE (
    ITEM VARCHAR(100),
    TYPE VARCHAR(25)
);
CREATE TABLE PILL (
    ITEM VARCHAR(100),
    TYPE VARCHAR(25)
);

CREATE TABLE GAS (
    STREET VARCHAR(100), 
    LINE VARCHAR(50)
);
CREATE TABLE MARKET (
    STREET VARCHAR(100), 
    LINE VARCHAR(50)
);